cc_library(
    name = "parse_queue",
    srcs = ["parse_queue.cpp"],
    hdrs = ["parse_queue.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//base",
        "//json:jsoncpp",
        "//util/process:subprocess",
        "//util/thread:work_queue",
    ],
)
