cc_binary(
    name = "server",
    srcs = [
        "server.cpp",
    ],
    deps = [
        "//base",
        "//inferui/eval:eval_app_util",
        "//inferui/eval:eval_util",
        "//inferui/model",
        "//json:jsonrpc",
        "//util/recordio",
    ],
)

cc_binary(
    name = "studio",
    srcs = [
        "studio.cpp",
    ],
    deps = [
        "//base",
        "//inferui/eval:eval_app_util",
        "//inferui/eval:eval_util",
        "//inferui/model",
        "//json:jsonrpc",
        "//util/recordio",
    ],
)
